title: Picture Box of McDoughnut
email: natthamon.ng@gmail.com
description: >-
  Website created for study purpose
baseurl: "/20191022-Picture-box-jekyll" # the subpath of your site, e.g. /blog
url: "https://natthamonng.github.io/20191022-Picture-box-jekyll/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ngnatthamon
github_username:  natthamonng

plugins:
  - jekyll-feed
  - jekyll-seo-tag

